import type { Metadata } from "next";
import { Koulen } from "next/font/google";
import "./globals.css";


const koulen = Koulen({
  variable: "--font-koulen",
  subsets: ["khmer"],
  weight: "400", // Add the weight property
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${koulen.variable} ${koulen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
