import type { Metadata } from "next";
import { Koulen } from "next/font/google";
import "./globals.css";
import { HeaderContextProvider } from '../../components/context/headerContext';
import { FootContextProvider } from "../../components/context/footContext";




const koulen = Koulen({
  variable: "--font-koulen",
  subsets: ["khmer"],
  weight: "400", // Add the weight property
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${koulen.variable} ${koulen.variable} antialiased`}
        >
        <HeaderContextProvider>
        <FootContextProvider>
            {children}
          </FootContextProvider>
        </HeaderContextProvider>
      </body>
    </html>
  );
}
